const PRODUCTOS=[   
    {id:1,categorias:"Raquetas", marca:"Babolat", modelo:"Pure Aero Rafa", precio:82500, imagen:"./images/raquetas/babolatrafa.jpg",cantidad:1},
    {id:2,categorias:"Raquetas", marca:"Babolat", modelo:"Pure Drive", precio:78500, imagen:"./images/raquetas/babolatdrive.png",cantidad:1},
    {id:3,categorias:"Raquetas", marca:"Babolat", modelo:"Pure Aero", precio:78500, imagen:"./images/raquetas/babolataero.png",cantidad:1},
    {id:4,categorias:"Raquetas", marca:"Babolat", modelo:"Pure Aero Strike", precio:70200, imagen:"./images/raquetas/babolatstrike.png",cantidad:1},
    {id:5,categorias:"Raquetas", marca:"HEAD", modelo:"EXTREME TOUR", precio:67500, imagen:"./images/raquetas/extreme-tour-2022.jpg",cantidad:1},
    {id:6,categorias:"Raquetas", marca:"HEAD", modelo:"BOOM PRO", precio:70000, imagen:"./images/raquetas/boom-pro-2022.jpg",cantidad:1},
    {id:7,categorias:"Raquetas", marca:"HEAD", modelo:"SPEED PRO", precio:75000, imagen:"./images/raquetas/speed-pro-2022.jpg",cantidad:1},
    {id:8,categorias:"Raquetas", marca:"HEAD", modelo:"RADICAL PRO", precio:67500, imagen:"./images/raquetas/radical-pro.jpg",cantidad:1},
    {id:9,categorias:"Raquetas", marca:"HEAD", modelo:"PRESTIGE PRO", precio:75500, imagen:"./images/raquetas/prestige-pro-2021.jpg",cantidad:1},
    {id:10,categorias:"Raquetas", marca:"Wilson", modelo:"Blade 98 V8.0", precio:67500, imagen:"./images/raquetas/blade.jpeg",cantidad:1},
    {id:11,categorias:"Raquetas", marca:"Wilson", modelo:"PRO Staff RF 97", precio:75500, imagen:"./images/raquetas/prostaff.jpeg",cantidad:1},
    {id:12,categorias:"Raquetas", marca:"Wilson", modelo:"Clash 98 V2", precio:70500, imagen:"./images/raquetas/clash.jpeg",cantidad:1},
    {id:13,categorias:"Raquetas", marca:"Wilson", modelo:"Burn 100 CV", precio:67500, imagen:"./images/raquetas/burn.jpg",cantidad:1},
    {id:14,categorias:"Raquetas", marca:"Wilson", modelo:"Ultra 100 V4", precio:67500, imagen:"./images/raquetas/wilsonultra3.jpeg",cantidad:1},
    {id:15,categorias:"Raquetas", marca:"HEAD", modelo:"GRAVITY PRO", precio:67500, imagen:"./images/raquetas/gravity-pro.jpg",cantidad:1},    
    {id:16,categorias:"Cordajes", marca:"HEAD", modelo:"LYNX TOUCH",tipo: "Monofilamento", precio:3700, imagen:"./images/cordajes/lynx-green.jpg",cantidad:1},
    {id:17,categorias:"Cordajes", marca:"HEAD", modelo:"HAWK TM",tipo: "Monofilamento", precio:5000, imagen:"./images/cordajes/hawk-black.jpg",cantidad:1},
    {id:18,categorias:"Cordajes", marca:"HEAD", modelo:"HAWK ROUGH",tipo: "Monofilamento", precio:6200, imagen:"./images/cordajes/hawk-rough-anthracite.jpg",cantidad:1},
    {id:19,categorias:"Cordajes", marca:"HEAD", modelo:"HAWK TOUCH",tipo: "Monofilamento", precio:5000, imagen:"./images/cordajes/hawk-touch-red.jpg",cantidad:1},
    {id:20,categorias:"Cordajes", marca:"HEAD", modelo:"INTELLITOUR",tipo: "Hibrido", precio:4700, imagen:"./images/cordajes/cuerda-babolat-rpm-blast-12m-11-29d0fa1a9c813febd216625676863632-480-0.jpg",cantidad:1},
    {id:21,categorias:"Cordajes", marca:"HEAD", modelo:"REFLEX MLT",tipo: "Multifilamento", precio:5500, imagen:"./images/cordajes/reflex-mlt-natural.jpg",cantidad:1},
    {id:22,categorias:"Cordajes", marca:"HEAD", modelo:"RIP CONTROL",tipo: "Multifilamento", precio:4000, imagen:"./images/cordajes/rip-control-orange.jpg",cantidad:1},
    {id:23,categorias:"Cordajes", marca:"HEAD", modelo:"VELOCITY MLT",tipo: "Multifilamento", precio:3300, imagen:"./images/cordajes/velocity-mlt-natural.jpg",cantidad:1},
    {id:30,categorias:"Cordajes", marca:"Babolat", modelo:"RPM Blast",tipo: "Monofilamento", precio:4700, imagen:"./images/cordajes/cuerda-babolat-rpm-blast-12m-11-29d0fa1a9c813febd216625676863632-480-0.jpg",cantidad:1},
    {id:28,categorias:"Cordajes", marca:"Babolat", modelo:"Addixion Comfort",tipo: "Monofilamento", precio:4700, imagen:"./images/cordajes/cuerda-babolat-addixion-12m-111-9aafdbfd84f0fc486b16625676208542-480-0.jpg",cantidad:1},
    {id:29,categorias:"Cordajes", marca:"Babolat", modelo:"RPM Soft",tipo: "Monofilamento", precio:4700, imagen:"./images/cordajes/cuerda-babolat-rpm-soft-12m-11-f978a71f5032aa9d8916633624704691-480-0.jpg",cantidad:1},
    {id:30,categorias:"Cordajes", marca:"Babolat", modelo:"RPM Hurricane",tipo: "Monofilamento", precio:4700, imagen:"./images/cordajes/cuerda-babolat-rpm-hurricane-12m-11-0dcb371f04dd38b7d816625680667746-480-0.jpg",cantidad:1},
    {id:28,categorias:"Cordajes", marca:"Wilson", modelo:"NXT Duo II",tipo: "Monofilamento", precio:8700, imagen:"./images/cordajes/wilsonhibrido.jpg",cantidad:1},
    {id:29,categorias:"Cordajes", marca:"Wilson", modelo:"NXT Power",tipo: "Multifilamento", precio:7000, imagen:"./images/cordajes/wilsonmulti.png",cantidad:1},
    {id:30,categorias:"Cordajes", marca:"Wilson", modelo:"NXT 16 Comfort",tipo: "Multifilamento", precio:7000, imagen:"./images/cordajes/wilsonmult.jpeg",cantidad:1},
    {id:31,categorias:"Grips", marca:"HEAD", modelo:"SOFTAC TRACTION", precio:2000, imagen:"./images/grips/softac-traction.jpg",cantidad:1},
    {id:33,categorias:"Grips", marca:"HEAD", modelo:"LEATHER TOUR", precio:3700, imagen:"./images/grips/leather-tour-brown.jpg",cantidad:1},
    {id:32,categorias:"Grips", marca:"HEAD", modelo:"HYDROSORB PRO", precio:2200, imagen:"./images/grips/hydrosorb-pro-white.jpg",cantidad:1},
    {id:34,categorias:"Grips", marca:"HEAD", modelo:"ULTIMATE", precio:3000, imagen:"../images/grips/ultimate-black.jpg",cantidad:1},
    {id:35,categorias:"Grips", marca:"HEAD", modelo:"ABSORBING", precio:1750, imagen:"./images/grips/dual-absorbing-black.jpg",cantidad:1},
    {id:36,categorias:"Grips", marca:"Babolat", modelo:"Syntec Pro", precio:2600, imagen:"./images/grips/grip-babolat-syntecpro-white1-30ef20b2bbd1eefaa516615247377181-480-0.jpg",cantidad:1},
    {id:37,categorias:"Grips", marca:"Babolat", modelo:"Syntec Uptake", precio:2200, imagen:"./images/grips/670069105-69de03fb6b2841551916039124756703-640-0.jpg",cantidad:1},
    {id:38,categorias:"Grips", marca:"Wilson", modelo:"Classic Sponge", precio:2400, imagen:"../images/grips/wrz4205bke_0_cushion_aire_classic_sponge-1200x1200.jpeg",cantidad:1},
    {id:39,categorias:"Grips", marca:"Wilson", modelo:"Sublime Feel", precio:2400, imagen:"./images/grips/wrz4202whe_0_sublime_white-1200x1200_1.jpeg",cantidad:1},
    {id:40,categorias:"Grips", marca:"Wilson", modelo:"Cushion Pro", precio:1600, imagen:"./images/grips/wrz4209bk_0_cushion_pro-1200x1200.jpeg",cantidad:1}
]

ElementosCarrito= JSON.parse(localStorage.getItem("carrito",)) || [];

